branches-template:
  - main: "v{{major}}.{{minor}}.{{patch}}-{{date}}, {{dist-tag}}"
  - "feature/*": "feature-{{ref-name}}-{{timestamp}}, {{dist-tag}}"
  - "bugfix/*": "bugfix-{{ref-name}}-{{timestamp}}, {{dist-tag}}"
  - tag: "v{{major}}.{{minor}}.{{patch}}, {{dist-tag}}"

dist-tags:
  - main: "latest"
  - "feature/*": "dev"
  - "bugfix/*": "dev"
  - tag: "stable"
